import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../../components/navbar";
import { Footer } from "../../components/footer";
import { Card } from "../../components/cardinfo.tsx/card";
import WaterDashboard from "../../components/waterdashboard/Waterdashboard";
// This import was likely incorrect for a favicon and is not needed if the SVG is a component.
// import '../app/give-water-ocean-drink-sea-svgrepo-com.svg' 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "INFO WATER",
  description: "Generated by create next app",
};

// WaterIcon component definition has been moved to a separate file (e.g., components/WaterIcon.tsx)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon link */}
        {/* Changed href="save.png" to href="/save.png" to correctly reference the file in the public directory */}
        {/* If your favicon is `give-water.png` and it's in the `public` folder, use `/give-water.png` */}
        {/* You may also consider converting your SVG to .ico or .png for wider browser compatibility as a favicon. */}
        <link rel="icon" href="/water.svg" />
        <link rel="icon" type="image/png" sizes="32x32" /> 
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <Card />
        <WaterDashboard />
        {children}
        <Footer />
      </body>
    </html>
  );
}
